[project]
name = "deckofcardsmcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.12.5",
    "httpx>=0.27.2",
    "pylint>=4.0.2",
    "pytest>=8.3.3",
    "pytest-asyncio>=0.24.0",
]
